version: '3.7'

services:
  web:
    build: ./
    container_name: secure_mes_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: secure_mes_db
    volumes:
      - secure_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  secure_postgres_data: