# Generated by Django 4.0.4 on 2022-06-08 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allowed_users',
            field=models.ManyToManyField(null=True, related_name='allowed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
