# Generated by Django 4.0.4 on 2022-04-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_invite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('from_user', 'to_user')},
        ),
    ]
