# Generated by Django 4.0.4 on 2022-04-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_messages', to='mes_app.key'),
        ),
    ]
